---
- name: Simple RDS database creation
  hosts: localhost
  roles:
    - mysql

- name: Simple wordpress installation 
  hosts: aws_ec2
  gather_facts: true
  roles:
    - nginx
    - php
    - wordpress


